### ISSUE TITLE
Navigating to a def without examples keeps the code view from loading

### ISSUE THREAD

**Issue by samertm** [sourcegraph/sourcegraph.com#364]
See https://sourcegraph.com/github.com/grimreaper/accursed@master/.JavaArtifact/default-group/src/app/.def/com/eitanadler/accursed/activities/DiceDetails:type

Even though https://sourcegraph.com/github.com/grimreaper/accursed@master/.tree/app/src/main/java/com/eitanadler/accursed/activities/DiceDetails.java loads fine.

cc @grimreaper

**Comment by gbbr** [comment]
The problem here is that there are 2 slashes in the URL, and when you open the link, one of them is automatically removed by the browser. Not sure if this is coming from `srclib` or the app but will investigate.

![screen shot 2015-02-15 at 10 17 26 pm](https://cloud.githubusercontent.com/assets/6686356/6203999/9a38c304-b560-11e4-843a-65aa30d23c7b.png)

**Comment by gbbr** [comment]
This should no longer occur, if it does, please re-open. I suspect the problem might be in the analyzer though (notice the "double-slash")
