### ISSUE TITLE
Don't immediately resolve tags/branches in URLs

### ISSUE THREAD

**Issue by peterbourgon** [sourcegraph/sourcegraph.com#394]
I go to a SourceGraph URL that includes a tag or branch, e.g. 

&nbsp;&nbsp;&nbsp;[https://sourcegraph.com/github.com/go-kit/kit@**master**/.tree/addsvc/main.go](https://sourcegraph.com/github.com/go-kit/kit@master/.tree/addsvc/main.go)

I want to share this link with someone else, for example in a GitHub PR, to reference a file or definition.

Expected behavior: the URL remains fully referential in the URL bar, e.g. master is still called master, so when I copy/paste it, it's pointing to the most recent commit on the branch.

Actual behavior: the tag/branch in the URL is immediately modified to its complete git SHA1, e.g. master becomes 8662... (at time of writing). When I copy/paste it, it's stuck at a fixed point in time. I have to manually replace 8662... with master.

GitHub has a nice mechanism for this: if you want the resolved, permalink-style URL, the keyboard shortcut _y_ takes you there.

**Comment by beyang** [comment]
thanks for filing! @gbbr is this still an issue on the nodb branch?

**Comment by gbbr** [comment]
It does, this is well known behavior and was the result of compromise. When we request all definitions for a file they are linked to SHA-1 instead of branch name so we have compromised on standardizing using SHA-1's throughout the site.

I am aware of this issue and it has been in my backlog for quite some time now. I can definitely see the inconvenience it can cause and should get to it soon.

Thanks for reporting it @peterbourgon

**Comment by gbbr** [comment]
I have resolved this in nodb.

**Comment by beyang** [comment]
FYI this may take awhile to show up on https://sourcegraph.com (it's currently on a feature branch yet to be merged into master and deployed)

**Comment by peterbourgon** [comment]
:sunglasses:
