### ISSUE TITLE
Identically worded Sourcegraph requests being filed on Mattermost repo

### ISSUE THREAD

**Issue by it33** [sourcegraph/sourcegraph.com#405]
Our repo, https://github.com/mattermost/platform/issues, is getting multiple identical requests for the Admins to use Sourcegraph. We're not comfortable with the Sourcegraph Terms of Service, so we declined the first time, and these identical requests keep rolling in. 

They read: 

I want to use Sourcegraph for platform code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/mattermost/platform. (It should only take 30 seconds.)

Thank you!

Not sure what's causing this, I'm assuming it's unintentional? 

https://github.com/mattermost/platform/issues/190
https://github.com/mattermost/platform/issues/179
https://github.com/mattermost/platform/issues/95

**Comment by sqs** [comment]
Sorry about this. This is caused by users who submit the request, not by us directly. When they look up your repo on Sourcegraph, it tells them they need to request that an admin enable the repo, and it links them to a pre-filled GitHub issue form with the filled-in request.

I have disabled mattermost on Sourcegraph, so users will not be able to make this request anymore: https://sourcegraph.com/github.com/mattermost/platform (it now 404s).

**Comment by it33** [comment]
Thanks @sqs!
